// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	Empty
	Device
	DeviceList
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Device struct {
	// The name of the device
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto1.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DeviceList struct {
	// List of Devices
	Device []*Device `protobuf:"bytes,1,rep,name=device" json:"device,omitempty"`
}

func (m *DeviceList) Reset()                    { *m = DeviceList{} }
func (m *DeviceList) String() string            { return proto1.CompactTextString(m) }
func (*DeviceList) ProtoMessage()               {}
func (*DeviceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeviceList) GetDevice() []*Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*Device)(nil), "proto.Device")
	proto1.RegisterType((*DeviceList)(nil), "proto.DeviceList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SonosService service

type SonosServiceClient interface {
	ListDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeviceList, error)
}

type sonosServiceClient struct {
	cc *grpc.ClientConn
}

func NewSonosServiceClient(cc *grpc.ClientConn) SonosServiceClient {
	return &sonosServiceClient{cc}
}

func (c *sonosServiceClient) ListDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeviceList, error) {
	out := new(DeviceList)
	err := grpc.Invoke(ctx, "/proto.SonosService/ListDevices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SonosService service

type SonosServiceServer interface {
	ListDevices(context.Context, *Empty) (*DeviceList, error)
}

func RegisterSonosServiceServer(s *grpc.Server, srv SonosServiceServer) {
	s.RegisterService(&_SonosService_serviceDesc, srv)
}

func _SonosService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonosServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SonosService/ListDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonosServiceServer).ListDevices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SonosService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SonosService",
	HandlerType: (*SonosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDevices",
			Handler:    _SonosService_ListDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto1.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xec, 0x5c, 0xac,
	0xae, 0xb9, 0x05, 0x25, 0x95, 0x4a, 0x32, 0x5c, 0x6c, 0x2e, 0xa9, 0x65, 0x99, 0xc9, 0xa9, 0x42,
	0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6,
	0x92, 0x31, 0x17, 0x17, 0x44, 0xd6, 0x27, 0xb3, 0xb8, 0x44, 0x48, 0x95, 0x8b, 0x2d, 0x05, 0xcc,
	0x93, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0xe2, 0x85, 0x98, 0xa9, 0x07, 0x51, 0x12, 0x04, 0x95,
	0x34, 0x72, 0xe0, 0xe2, 0x09, 0xce, 0xcf, 0xcb, 0x2f, 0x0e, 0x4e, 0x2d, 0x02, 0x1b, 0x6c, 0xc0,
	0xc5, 0x0d, 0xd2, 0x0e, 0x51, 0x55, 0x2c, 0xc4, 0x03, 0xd5, 0x05, 0xb6, 0x5f, 0x4a, 0x10, 0xc5,
	0x0c, 0x90, 0x3a, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x98, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x88,
	0xfa, 0x99, 0x27, 0xbb, 0x00, 0x00, 0x00,
}
